#!/usr/bin/env python3
"""
将 MySQL EBS 数据库脚本转换为 PostgreSQL 语法
"""

import re
import os

def convert_mysql_to_postgres(mysql_sql):
    """将 MySQL SQL 转换为 PostgreSQL 语法"""
    
    # 1. 移除 MySQL 特定的语句
    lines = mysql_sql.split('\n')
    postgres_lines = []
    
    for line in lines:
        # 跳过 MySQL 特定的语句
        if line.strip().startswith('SET FOREIGN_KEY_CHECKS'):
            continue
        if 'ENGINE=InnoDB' in line:
            line = line.replace('ENGINE=InnoDB', '')
        if 'DEFAULT CHARSET=utf8mb4' in line:
            line = line.replace('DEFAULT CHARSET=utf8mb4', '')
        
        # 2. 转换反引号为双引号
        line = line.replace('`', '"')
        
        # 3. 转换数据类型
        line = re.sub(r'bit\(1\)', 'boolean', line)
        line = re.sub(r'bit\(\)', 'boolean', line)
        line = re.sub(r'tinyint', 'smallint', line)
        line = re.sub(r'smallint\([^)]*\)', 'smallint', line)
        line = re.sub(r'int\([^)]*\)', 'integer', line)
        line = re.sub(r'bigint\([^)]*\)', 'bigint', line)
        line = re.sub(r'decimal\(([^)]*)\)', r'numeric(\1)', line)
        line = re.sub(r'datetime', 'timestamp', line)
        line = re.sub(r'CURRENT_TIMESTAMP', 'CURRENT_TIMESTAMP', line)
        line = re.sub(r'text\s+COMMENT', 'text', line)
        
        # 4. 转换默认值
        line = re.sub(r"b'0'", 'false', line)
        line = re.sub(r"b'1'", 'true', line)
        
        # 5. 转换注释语法
        if 'COMMENT' in line:
            # 提取注释内容
            comment_match = re.search(r"COMMENT\s+'([^']*)'", line)
            if comment_match:
                comment = comment_match.group(1)
                # 移除 COMMENT 部分，PostgreSQL 使用单独的 COMMENT ON 语句
                line = re.sub(r"COMMENT\s+'[^']*'", '', line)
                # 我们会在后面单独添加 COMMENT ON 语句
        
        # 6. 转换索引语法
        if 'UNIQUE KEY' in line:
            line = line.replace('UNIQUE KEY', 'CONSTRAINT')
            # 提取约束名和列
            match = re.search(r'CONSTRAINT\s+"([^"]+)"\s*\(([^)]+)\)', line)
            if match:
                constraint_name = match.group(1)
                columns = match.group(2)
                line = f'  CONSTRAINT "{constraint_name}" UNIQUE ({columns})'
        
        elif 'KEY' in line and not 'PRIMARY KEY' in line and not 'FOREIGN KEY' in line:
            # 普通索引转换为 CREATE INDEX 语句
            match = re.search(r'KEY\s+"([^"]+)"\s*\(([^)]+)\)', line)
            if match:
                index_name = match.group(1)
                columns = match.group(2)
                table_match = re.search(r'CREATE TABLE\s+"([^"]+)"', '\n'.join(postgres_lines[-10:]))
                if table_match:
                    table_name = table_match.group(1)
                    # 我们会在后面单独添加 CREATE INDEX 语句
                    line = f'-- INDEX: {index_name} on ({columns})'
                else:
                    line = f'-- {line.strip()}'
        
        # 7. 转换自增
        line = re.sub(r'AUTO_INCREMENT', 'GENERATED BY DEFAULT AS IDENTITY', line)
        
        postgres_lines.append(line)
    
    # 重新组合并处理注释和索引
    postgres_sql = '\n'.join(postgres_lines)
    
    # 8. 添加外键约束（PostgreSQL 使用不同的语法）
    # 我们保持 ALTER TABLE 语句，但需要调整语法
    postgres_sql = re.sub(
        r'ALTER TABLE\s+"([^"]+)"\s+ADD CONSTRAINT\s+"([^"]+)"\s+FOREIGN KEY\s*\(([^)]+)\)\s+REFERENCES\s+"([^"]+)"\s*\(([^)]+)\)\s+(ON DELETE\s+[^;]*)?;',
        r'ALTER TABLE "\1" ADD CONSTRAINT "\2" FOREIGN KEY (\3) REFERENCES "\4" (\5) \6;',
        postgres_sql
    )
    
    # 9. 确保每个语句以分号结束
    statements = postgres_sql.split(';')
    cleaned_statements = []
    
    for stmt in statements:
        stmt = stmt.strip()
        if stmt:
            if not stmt.endswith(';'):
                stmt += ';'
            cleaned_statements.append(stmt)
    
    return '\n\n'.join(cleaned_statements)

def main():
    # 读取原始 MySQL 脚本
    mysql_file = "文档/34_EBS业务数据库表结构_SQL脚本.sql"
    
    if not os.path.exists(mysql_file):
        print(f"错误: 文件 {mysql_file} 不存在")
        return
    
    with open(mysql_file, 'r', encoding='utf-8') as f:
        mysql_sql = f.read()
    
    print(f"读取 MySQL 脚本: {mysql_file} ({len(mysql_sql)} 字符)")
    
    # 转换为 PostgreSQL
    postgres_sql = convert_mysql_to_postgres(mysql_sql)
    
    # 保存 PostgreSQL 版本
    postgres_file = "文档/ebs_tables_postgres_full.sql"
    with open(postgres_file, 'w', encoding='utf-8') as f:
        f.write(postgres_sql)
    
    print(f"PostgreSQL 脚本已保存: {postgres_file}")
    print(f"PostgreSQL 脚本大小: {len(postgres_sql)} 字符")
    
    # 创建简化的导入脚本
    create_import_script(postgres_file)

def create_import_script(postgres_file):
    """创建导入脚本"""
    
    import_script = """#!/usr/bin/env python3
"""
EBS 数据库表导入脚本
"""

import psycopg2
import sys
import os

def import_ebs_tables():
    \"\"\"导入 EBS 表结构到 PostgreSQL\"\"\"
    
    connection_params = {
        'host': 'localhost',
        'port': 5432,
        'database': 'FrontCRM',
        'user': 'postgres',
        'password': '1234'
    }
    
    sql_file = "文档/ebs_tables_postgres_full.sql"
    
    if not os.path.exists(sql_file):
        print(f"错误: SQL 文件 {sql_file} 不存在")
        return False
    
    try:
        print("正在连接到 PostgreSQL...")
        conn = psycopg2.connect(**connection_params)
        conn.autocommit = True
        cursor = conn.cursor()
        
        print("连接成功!")
        
        # 读取 SQL 文件
        with open(sql_file, 'r', encoding='utf-8') as f:
            sql_content = f.read()
        
        print(f"读取 SQL 文件: {sql_file} ({len(sql_content)} 字符)")
        
        # 分割 SQL 语句
        statements = sql_content.split(';')
        
        print("正在导入表结构...")
        
        for i, stmt in enumerate(statements):
            stmt = stmt.strip()
            if not stmt:
                continue
                
            # 添加分号
            if not stmt.endswith(';'):
                stmt += ';'
            
            try:
                cursor.execute(stmt)
                print(f"  [{i+1}/{len(statements)}] 执行成功")
            except Exception as e:
                print(f"  [{i+1}/{len(statements)}] 执行失败: {e}")
                print(f"    语句: {stmt[:100]}...")
        
        # 验证导入
        print("\\n验证导入的表...")
        cursor.execute(\"""
            SELECT table_schema, table_name, table_type 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            ORDER BY table_name
        \""")
        
        tables = cursor.fetchall()
        print(f"已创建的表 ({len(tables)}):")
        
        table_groups = {}
        for table in tables:
            schema, name, type_ = table
            prefix = name.split('_')[0] if '_' in name else name[:10]
            if prefix not in table_groups:
                table_groups[prefix] = []
            table_groups[prefix].append(name)
        
        for prefix, tables_list in table_groups.items():
            print(f"  {prefix}*: {len(tables_list)} 个表")
            for table_name in tables_list[:5]:  # 只显示前5个
                print(f"    - {table_name}")
            if len(tables_list) > 5:
                print(f"    ... 还有 {len(tables_list)-5} 个表")
        
        cursor.close()
        conn.close()
        
        print("\\n✅ EBS 表结构导入完成!")
        return True
        
    except Exception as e:
        print(f"错误: {str(e)}")
        return False

if __name__ == "__main__":
    print("=== EBS 数据库表导入工具 ===")
    print("数据库: FrontCRM")
    print("用户: postgres")
    print("密码: 1234")
    print()
    
    # 检查连接
    try:
        conn = psycopg2.connect(
            host='localhost',
            port=5432,
            database='FrontCRM',
            user='postgres',
            password='1234'
        )
        conn.close()
        print("✅ 数据库连接正常")
    except Exception as e:
        print(f"❌ 数据库连接失败: {e}")
        print("请检查:")
        print("1. PostgreSQL 服务是否运行")
        print("2. 数据库 FrontCRM 是否存在")
        print("3. 用户名/密码是否正确")
        sys.exit(1)
    
    # 询问确认
    response = input("\\n是否导入 EBS 表结构? (y/n): ")
    if response.lower() != 'y':
        print("取消导入")
        sys.exit(0)
    
    # 导入表结构
    if import_ebs_tables():
        print("\\n✅ 导入成功!")
    else:
        print("\\n❌ 导入失败")
        sys.exit(1)
"""
    
    import_file = "import_ebs_tables.py"
    with open(import_file, 'w', encoding='utf-8') as f:
        f.write(import_script)
    
    print(f"导入脚本已创建: {import_file}")
    print("\\n使用方法:")
    print(f"1. 确保 PostgreSQL 服务正在运行")
    print(f"2. 确保 FrontCRM 数据库已创建")
    print(f"3. 运行: python {import_file}")
    print(f"4. 或者直接执行: psql -h localhost -p 5432 -U postgres -d FrontCRM -f 文档/ebs_tables_postgres_full.sql")

if __name__ == "__main__":
    main()