// <auto-generated />
using System;
using CRM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317170015_AddSalesAndPurchaseOrderTables")]
    partial class AddSalesAndPurchaseOrderTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM.Core.Models.Component.ComponentCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AlternativesJson")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsRoHSCompliant")
                        .HasColumnType("boolean");

                    b.Property<string>("LifecycleStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Mpn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewsJson")
                        .HasColumnType("text");

                    b.Property<string>("PackageType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PriceTrendJson")
                        .HasColumnType("text");

                    b.Property<int>("QueryCount")
                        .HasColumnType("integer");

                    b.Property<string>("SellersJson")
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SpecsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Mpn")
                        .IsUnique();

                    b.ToTable("component_cache");
                });

            modelBuilder.Entity("CRM.Core.Models.Customer.CustomerAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("AddressId");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<short>("AddressType")
                        .HasColumnType("smallint");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<short?>("Country")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("customeraddress");
                });

            modelBuilder.Entity("CRM.Core.Models.Customer.CustomerBankInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("BankId");

                    b.Property<string>("AccountName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankBranch")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<short?>("Currency")
                        .HasColumnType("smallint");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("customerbankinfo");
                });

            modelBuilder.Entity("CRM.Core.Models.Customer.CustomerContactHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("HistoryId");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NextFollowUpTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Result")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("customercontacthistory");
                });

            modelBuilder.Entity("CRM.Core.Models.Customer.CustomerContactInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ContactId");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CName");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("EName");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short?>("Gender")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("IsMain");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("QQ")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tel")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Tel");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Title");

                    b.Property<string>("WeChat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("customercontactinfo");
                });

            modelBuilder.Entity("CRM.Core.Models.Customer.CustomerInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Application")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<short>("AscriptionType")
                        .HasColumnType("smallint");

                    b.Property<short?>("Background")
                        .HasColumnType("smallint");

                    b.Property<bool>("BlackList")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BlackListAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlackListByUserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("BlackListByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BlackListReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<short?>("CommonSeaAuditStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("CompanyInfo")
                        .HasColumnType("text");

                    b.Property<short?>("CompanyNature")
                        .HasColumnType("smallint");

                    b.Property<short?>("Country")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreditCode")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<decimal>("CreditLine")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CreditLineRemain")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DUNS")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<short?>("DealMode")
                        .HasColumnType("smallint");

                    b.Property<string>("DeleteReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("DeletedByUserName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("DisenableStatus")
                        .HasColumnType("boolean");

                    b.Property<short?>("DisenableType")
                        .HasColumnType("smallint");

                    b.Property<string>("ExternalNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short?>("IdentityType")
                        .HasColumnType("smallint");

                    b.Property<string>("Industry")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsControl")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric(10,6)");

                    b.Property<short>("Level")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric(10,6)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("NickName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OfficialName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<short?>("Payment")
                        .HasColumnType("smallint");

                    b.Property<string>("Product")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Product2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProtectFromUserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("ProtectStatus")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProtectTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SalesUserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short?>("Scale")
                        .HasColumnType("smallint");

                    b.Property<string>("StandardOfficialName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short?>("TradeCurrency")
                        .HasColumnType("smallint");

                    b.Property<short?>("TradeType")
                        .HasColumnType("smallint");

                    b.Property<short?>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("customerinfo");
                });

            modelBuilder.Entity("CRM.Core.Models.Purchase.PurchaseOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("PurchaseOrderId");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<decimal>("ConvertTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("convert_total");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Currency")
                        .HasColumnType("smallint")
                        .HasColumnName("currency");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_address");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_date");

                    b.Property<short>("ErrStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("err_status");

                    b.Property<short>("FinanceStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("finance_status");

                    b.Property<string>("InnerComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("inner_comment");

                    b.Property<short>("InvoiceStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("invoice_status");

                    b.Property<int>("ItemRows")
                        .HasColumnType("integer")
                        .HasColumnName("item_rows");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PurchaseGroupId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("purchase_group_id");

                    b.Property<string>("PurchaseOrderCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purchase_order_code");

                    b.Property<string>("PurchaseUserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("purchase_user_id");

                    b.Property<string>("PurchaseUserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("purchase_user_name");

                    b.Property<string>("SalesGroupId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("sales_group_id");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<short>("StockOutStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("stock_out_status");

                    b.Property<short>("StockStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("stock_status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<string>("VendorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vendor_code");

                    b.Property<string>("VendorContactId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("vendor_contact_id");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("vendor_id");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vendor_name");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderCode")
                        .IsUnique();

                    b.ToTable("purchaseorder");
                });

            modelBuilder.Entity("CRM.Core.Models.Purchase.PurchaseOrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("PurchaseOrderItemId");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<decimal>("Cost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Currency")
                        .HasColumnType("smallint")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_date");

                    b.Property<short>("ErrStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("err_status");

                    b.Property<short>("FinancePaymentStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("finance_payment_status");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PN")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pn");

                    b.Property<string>("ProductId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("product_id");

                    b.Property<string>("PurchaseOrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("qty");

                    b.Property<string>("SellOrderItemId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("sell_order_item_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short>("StockInStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("stock_in_status");

                    b.Property<short>("StockOutStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("stock_out_status");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("SellOrderItemId");

                    b.ToTable("purchaseorderitem");
                });

            modelBuilder.Entity("CRM.Core.Models.Quote.Quote", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("QuoteId");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mpn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mpn");

                    b.Property<string>("PurchaseUserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("purchase_user_id");

                    b.Property<string>("QuoteCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("quote_code");

                    b.Property<DateTime>("QuoteDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quote_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("RFQId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("rfq_id");

                    b.Property<string>("RFQItemId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("rfq_item_id");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("remark");

                    b.Property<string>("SalesUserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("sales_user_id");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("QuoteCode")
                        .IsUnique();

                    b.ToTable("quote");
                });

            modelBuilder.Entity("CRM.Core.Models.Quote.QuoteItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("QuoteItemId");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<string>("BrandOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand_origin");

                    b.Property<string>("ContactId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("contact_id");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_name");

                    b.Property<decimal?>("ConvertedPrice")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("converted_price");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Currency")
                        .HasColumnType("smallint")
                        .HasColumnName("currency");

                    b.Property<string>("DateCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("date_code");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("FreeShipping")
                        .HasColumnType("boolean")
                        .HasColumnName("free_shipping");

                    b.Property<short>("LabelType")
                        .HasColumnType("smallint")
                        .HasColumnName("label_type");

                    b.Property<string>("LeadTime")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lead_time");

                    b.Property<int>("MinPackageQty")
                        .HasColumnType("integer")
                        .HasColumnName("min_package_qty");

                    b.Property<string>("MinPackageUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("min_package_unit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Moq")
                        .HasColumnType("integer")
                        .HasColumnName("moq");

                    b.Property<string>("Mpn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mpn");

                    b.Property<short>("PackageOrigin")
                        .HasColumnType("smallint")
                        .HasColumnName("package_origin");

                    b.Property<string>("PriceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("price_type");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("quantity");

                    b.Property<string>("QuoteId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("quote_id");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int>("StockQty")
                        .HasColumnType("integer")
                        .HasColumnName("stock_qty");

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("unit_price");

                    b.Property<string>("VendorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vendor_code");

                    b.Property<string>("VendorId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("vendor_id");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vendor_name");

                    b.Property<short>("WaferOrigin")
                        .HasColumnType("smallint")
                        .HasColumnName("wafer_origin");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("quoteitem");
                });

            modelBuilder.Entity("CRM.Core.Models.RFQ.RFQ", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("rfq_id");

                    b.Property<short>("AssignMethod")
                        .HasColumnType("smallint")
                        .HasColumnName("assign_method");

                    b.Property<string>("Competitor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("competitor");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("customer_id");

                    b.Property<short>("Importance")
                        .HasColumnType("smallint")
                        .HasColumnName("importance");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry");

                    b.Property<bool>("IsLastInquiry")
                        .HasColumnType("boolean")
                        .HasColumnName("is_last_inquiry");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Product")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product");

                    b.Property<string>("ProjectBackground")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("project_background");

                    b.Property<short>("QuoteMethod")
                        .HasColumnType("smallint")
                        .HasColumnName("quote_method");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("RfqCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rfq_code");

                    b.Property<DateTime>("RfqDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rfq_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<short>("RfqType")
                        .HasColumnType("smallint")
                        .HasColumnName("rfq_type");

                    b.Property<string>("SalesUserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("sales_user_id");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<short>("TargetType")
                        .HasColumnType("smallint")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("RfqCode")
                        .IsUnique();

                    b.ToTable("rfq");
                });

            modelBuilder.Entity("CRM.Core.Models.RFQ.RFQItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("item_id");

                    b.Property<string>("Alternatives")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alternatives");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerBrand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_brand");

                    b.Property<string>("CustomerMpn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_mpn");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<decimal?>("MinPackageQty")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_package_qty");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Moq")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("moq");

                    b.Property<string>("Mpn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mpn");

                    b.Property<short>("PriceCurrency")
                        .HasColumnType("smallint")
                        .HasColumnName("price_currency");

                    b.Property<string>("ProductionDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("production_date");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(1m)
                        .HasColumnName("quantity");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("RfqId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("rfq_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<decimal?>("TargetPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target_price");

                    b.HasKey("Id");

                    b.HasIndex("RfqId");

                    b.ToTable("rfqitem");
                });

            modelBuilder.Entity("CRM.Core.Models.Sales.SellOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("SellOrderId");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<decimal>("ConvertTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("convert_total");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Currency")
                        .HasColumnType("smallint")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_address");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_date");

                    b.Property<short>("ErrStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("err_status");

                    b.Property<short>("FinancePaymentStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("finance_payment_status");

                    b.Property<short>("FinanceReceiptStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("finance_receipt_status");

                    b.Property<short>("InvoiceStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("invoice_status");

                    b.Property<int>("ItemRows")
                        .HasColumnType("integer")
                        .HasColumnName("item_rows");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PurchaseGroupId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("purchase_group_id");

                    b.Property<short>("PurchaseOrderStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("purchase_order_status");

                    b.Property<string>("SalesUserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("sales_user_id");

                    b.Property<string>("SalesUserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sales_user_name");

                    b.Property<string>("SellOrderCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sell_order_code");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<short>("StockInStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("stock_in_status");

                    b.Property<short>("StockOutStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("stock_out_status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SellOrderCode")
                        .IsUnique();

                    b.ToTable("sellorder");
                });

            modelBuilder.Entity("CRM.Core.Models.Sales.SellOrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("SellOrderItemId");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Currency")
                        .HasColumnType("smallint")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerPnNo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_pn_no");

                    b.Property<string>("DateCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("date_code");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_date");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PN")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pn");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price");

                    b.Property<string>("ProductId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("product_id");

                    b.Property<decimal>("PurchasedQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("purchased_qty");

                    b.Property<decimal>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("qty");

                    b.Property<string>("QuoteId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("quote_id");

                    b.Property<string>("SellOrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("sell_order_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SellOrderId");

                    b.ToTable("sellorderitem");
                });

            modelBuilder.Entity("CRM.Core.Models.System.SysErrorLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DataId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("DocumentNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResolveRemark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("sys_error_log");
                });

            modelBuilder.Entity("CRM.Core.Models.System.SysSerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentSequence")
                        .HasColumnType("integer");

                    b.Property<int?>("LastResetMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("LastResetYear")
                        .HasColumnType("integer");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("ResetByMonth")
                        .HasColumnType("boolean");

                    b.Property<bool>("ResetByYear")
                        .HasColumnType("boolean");

                    b.Property<int>("SequenceLength")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModuleCode")
                        .IsUnique();

                    b.ToTable("sys_serial_number");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "Customer",
                            ModuleName = "客户",
                            Prefix = "Cus",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 2,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "Vendor",
                            ModuleName = "供应商",
                            Prefix = "Ven",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 3,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "Inquiry",
                            ModuleName = "询价/需求",
                            Prefix = "INQ",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 4,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "Quotation",
                            ModuleName = "报价",
                            Prefix = "QUO",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 5,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "SalesOrder",
                            ModuleName = "销售订单",
                            Prefix = "SO",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 6,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "PurchaseOrder",
                            ModuleName = "采购订单",
                            Prefix = "PO",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 7,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "StockIn",
                            ModuleName = "入库",
                            Prefix = "SIN",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 8,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "StockOut",
                            ModuleName = "出库",
                            Prefix = "SOUT",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 9,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "Inventory",
                            ModuleName = "库存调整",
                            Prefix = "INV",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 10,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "Receipt",
                            ModuleName = "收款",
                            Prefix = "REC",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 11,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "Payment",
                            ModuleName = "付款",
                            Prefix = "PAY",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 12,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "InputInvoice",
                            ModuleName = "进项发票",
                            Prefix = "VINV",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        },
                        new
                        {
                            Id = 13,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSequence = 0,
                            ModuleCode = "OutputInvoice",
                            ModuleName = "销项发票",
                            Prefix = "SINV",
                            ResetByMonth = false,
                            ResetByYear = false,
                            SequenceLength = 4
                        });
                });

            modelBuilder.Entity("CRM.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Mobile");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PasswordChangeTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PasswordChangeTime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Password");

                    b.Property<string>("PasswordPlain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PasswordPlain");

                    b.Property<string>("RealName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("RealName");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Salt");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("Status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("CRM.Core.Models.Customer.CustomerAddress", b =>
                {
                    b.HasOne("CRM.Core.Models.Customer.CustomerInfo", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM.Core.Models.Customer.CustomerBankInfo", b =>
                {
                    b.HasOne("CRM.Core.Models.Customer.CustomerInfo", "Customer")
                        .WithMany("BankAccounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM.Core.Models.Customer.CustomerContactInfo", b =>
                {
                    b.HasOne("CRM.Core.Models.Customer.CustomerInfo", "Customer")
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM.Core.Models.Purchase.PurchaseOrderItem", b =>
                {
                    b.HasOne("CRM.Core.Models.Purchase.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Core.Models.Sales.SellOrderItem", "SellOrderItem")
                        .WithMany()
                        .HasForeignKey("SellOrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("SellOrderItem");
                });

            modelBuilder.Entity("CRM.Core.Models.Quote.QuoteItem", b =>
                {
                    b.HasOne("CRM.Core.Models.Quote.Quote", "Quote")
                        .WithMany("Items")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("CRM.Core.Models.RFQ.RFQItem", b =>
                {
                    b.HasOne("CRM.Core.Models.RFQ.RFQ", "RFQ")
                        .WithMany("Items")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RFQ");
                });

            modelBuilder.Entity("CRM.Core.Models.Sales.SellOrderItem", b =>
                {
                    b.HasOne("CRM.Core.Models.Sales.SellOrder", "SellOrder")
                        .WithMany("Items")
                        .HasForeignKey("SellOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellOrder");
                });

            modelBuilder.Entity("CRM.Core.Models.Customer.CustomerInfo", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BankAccounts");

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("CRM.Core.Models.Purchase.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CRM.Core.Models.Quote.Quote", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CRM.Core.Models.RFQ.RFQ", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CRM.Core.Models.Sales.SellOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
