/** ISO 3166-1 国家/地区主数据（品牌模块）。由 scripts/gen-biz-brand-country-data.mjs 生成。 */
export type BizBrandCountryRaw = readonly [labelZh: string, code: string, nameEn: string, ...aliases: string[]]

export const BIZ_BRAND_COUNTRY_RAW: readonly BizBrandCountryRaw[] = [
  ["中国", "CN", "China", "PRC"],
  ["中国台湾", "TW", "Taiwan"],
  ["香港", "HK", "Hong Kong"],
  ["澳门", "MO", "Macao", "Macau"],
  ["美国", "US", "United States", "USA", "America"],
  ["日本", "JP", "Japan"],
  ["韩国", "KR", "South Korea", "Korea", "Republic of Korea"],
  ["德国", "DE", "Germany"],
  ["英国", "GB", "United Kingdom", "UK", "Great Britain"],
  ["法国", "FR", "France"],
  ["荷兰", "NL", "Netherlands", "Holland"],
  ["意大利", "IT", "Italy"],
  ["新加坡", "SG", "Singapore"],
  ["马来西亚", "MY", "Malaysia"],
  ["印度", "IN", "India"],
  ["越南", "VN", "Vietnam"],
  ["泰国", "TH", "Thailand"],
  ["瑞士", "CH", "Switzerland"],
  ["加拿大", "CA", "Canada"],
  ["以色列", "IL", "Israel"],
  ["瑞典", "SE", "Sweden"],
  ["芬兰", "FI", "Finland"],
  ["澳大利亚", "AU", "Australia"],
  ["墨西哥", "MX", "Mexico"],
  ["巴西", "BR", "Brazil"],
  ["俄罗斯", "RU", "Russia", "Russian Federation"],
  ["波兰", "PL", "Poland"],
  ["西班牙", "ES", "Spain"],
  ["比利时", "BE", "Belgium"],
  ["奥地利", "AT", "Austria"],
  ["捷克", "CZ", "Czech Republic", "Czechia"],
  ["匈牙利", "HU", "Hungary"],
  ["菲律宾", "PH", "Philippines"],
  ["印度尼西亚", "ID", "Indonesia"],
  ["沙特阿拉伯", "SA", "Saudi Arabia"],
  ["阿联酋", "AE", "United Arab Emirates", "UAE"],
  ["土耳其", "TR", "Turkey"],
  ["南非", "ZA", "South Africa"],
  ["新西兰", "NZ", "New Zealand"],
  ["阿尔巴尼亚", "AL", "Albania"],
  ["阿尔及利亚", "DZ", "Algeria"],
  ["阿富汗", "AF", "Afghanistan"],
  ["阿根廷", "AR", "Argentina"],
  ["阿鲁巴", "AW", "Aruba"],
  ["阿曼", "OM", "Oman"],
  ["阿塞拜疆", "AZ", "Azerbaijan"],
  ["埃及", "EG", "Egypt"],
  ["埃塞俄比亚", "ET", "Ethiopia"],
  ["爱尔兰", "IE", "Ireland"],
  ["爱沙尼亚", "EE", "Estonia"],
  ["安道尔", "AD", "Andorra"],
  ["安哥拉", "AO", "Angola"],
  ["安圭拉", "AI", "Anguilla"],
  ["安提瓜和巴布达", "AG", "Antigua and Barbuda"],
  ["奥兰群岛", "AX", "Aland Islands"],
  ["巴巴多斯", "BB", "Barbados"],
  ["巴布亚新几内亚", "PG", "Papua New Guinea"],
  ["巴哈马", "BS", "Bahamas"],
  ["巴基斯坦", "PK", "Pakistan"],
  ["巴拉圭", "PY", "Paraguay"],
  ["巴勒斯坦", "PS", "Palestine"],
  ["巴林", "BH", "Bahrain"],
  ["巴拿马", "PA", "Panama"],
  ["白俄罗斯", "BY", "Belarus"],
  ["百慕大", "BM", "Bermuda"],
  ["保加利亚", "BG", "Bulgaria"],
  ["北马里亚纳群岛", "MP", "Northern Mariana Islands"],
  ["北马其顿", "MK", "North Macedonia"],
  ["贝宁", "BJ", "Benin"],
  ["冰岛", "IS", "Iceland"],
  ["波多黎各", "PR", "Puerto Rico"],
  ["波黑", "BA", "Bosnia and Herzegovina"],
  ["玻利维亚", "BO", "Bolivia"],
  ["博茨瓦纳", "BW", "Botswana"],
  ["不丹", "BT", "Bhutan"],
  ["布基纳法索", "BF", "Burkina Faso"],
  ["布隆迪", "BI", "Burundi"],
  ["布韦岛", "BV", "Bouvet Island"],
  ["朝鲜", "KP", "North Korea", "DPRK"],
  ["赤道几内亚", "GQ", "Equatorial Guinea"],
  ["丹麦", "DK", "Denmark"],
  ["东帝汶", "TL", "Timor-Leste"],
  ["多哥", "TG", "Togo"],
  ["多米尼加", "DO", "Dominican Republic"],
  ["多米尼克", "DM", "Dominica"],
  ["厄瓜多尔", "EC", "Ecuador"],
  ["厄立特里亚", "ER", "Eritrea"],
  ["法罗群岛", "FO", "Faroe Islands"],
  ["法属波利尼西亚", "PF", "French Polynesia"],
  ["法属圭亚那", "GF", "French Guiana"],
  ["法属南部领地", "TF", "French Southern Territories"],
  ["法属圣马丁", "MF", "Saint Martin"],
  ["梵蒂冈", "VA", "Vatican City"],
  ["斐济", "FJ", "Fiji"],
  ["佛得角", "CV", "Cape Verde"],
  ["福克兰群岛", "FK", "Falkland Islands"],
  ["冈比亚", "GM", "Gambia"],
  ["刚果（布）", "CG", "Republic of the Congo"],
  ["刚果（金）", "CD", "Democratic Republic of the Congo", "DRC"],
  ["哥伦比亚", "CO", "Colombia"],
  ["哥斯达黎加", "CR", "Costa Rica"],
  ["格林纳达", "GD", "Grenada"],
  ["格陵兰", "GL", "Greenland"],
  ["格鲁吉亚", "GE", "Georgia"],
  ["根西岛", "GG", "Guernsey"],
  ["古巴", "CU", "Cuba"],
  ["瓜德罗普", "GP", "Guadeloupe"],
  ["关岛", "GU", "Guam"],
  ["圭亚那", "GY", "Guyana"],
  ["哈萨克斯坦", "KZ", "Kazakhstan"],
  ["海地", "HT", "Haiti"],
  ["荷兰加勒比区", "BQ", "Caribbean Netherlands"],
  ["荷属圣马丁", "SX", "Sint Maarten"],
  ["赫德岛和麦克唐纳群岛", "HM", "Heard Island and McDonald Islands"],
  ["黑山", "ME", "Montenegro"],
  ["洪都拉斯", "HN", "Honduras"],
  ["基里巴斯", "KI", "Kiribati"],
  ["吉布提", "DJ", "Djibouti"],
  ["吉尔吉斯斯坦", "KG", "Kyrgyzstan"],
  ["几内亚", "GN", "Guinea"],
  ["几内亚比绍", "GW", "Guinea-Bissau"],
  ["加纳", "GH", "Ghana"],
  ["加蓬", "GA", "Gabon"],
  ["柬埔寨", "KH", "Cambodia"],
  ["津巴布韦", "ZW", "Zimbabwe"],
  ["喀麦隆", "CM", "Cameroon"],
  ["卡塔尔", "QA", "Qatar"],
  ["开曼群岛", "KY", "Cayman Islands"],
  ["科科斯群岛", "CC", "Cocos Islands"],
  ["科摩罗", "KM", "Comoros"],
  ["科特迪瓦", "CI", "Ivory Coast", "Cote d'Ivoire"],
  ["科威特", "KW", "Kuwait"],
  ["克罗地亚", "HR", "Croatia"],
  ["肯尼亚", "KE", "Kenya"],
  ["库克群岛", "CK", "Cook Islands"],
  ["库拉索", "CW", "Curacao"],
  ["拉脱维亚", "LV", "Latvia"],
  ["莱索托", "LS", "Lesotho"],
  ["老挝", "LA", "Laos"],
  ["黎巴嫩", "LB", "Lebanon"],
  ["立陶宛", "LT", "Lithuania"],
  ["利比里亚", "LR", "Liberia"],
  ["利比亚", "LY", "Libya"],
  ["列支敦士登", "LI", "Liechtenstein"],
  ["留尼汪", "RE", "Reunion"],
  ["卢森堡", "LU", "Luxembourg"],
  ["卢旺达", "RW", "Rwanda"],
  ["罗马尼亚", "RO", "Romania"],
  ["马达加斯加", "MG", "Madagascar"],
  ["马恩岛", "IM", "Isle of Man"],
  ["马尔代夫", "MV", "Maldives"],
  ["马耳他", "MT", "Malta"],
  ["马拉维", "MW", "Malawi"],
  ["马里", "ML", "Mali"],
  ["马绍尔群岛", "MH", "Marshall Islands"],
  ["马提尼克", "MQ", "Martinique"],
  ["马约特", "YT", "Mayotte"],
  ["毛里求斯", "MU", "Mauritius"],
  ["毛里塔尼亚", "MR", "Mauritania"],
  ["美国本土外小岛屿", "UM", "US Minor Outlying Islands"],
  ["美属萨摩亚", "AS", "American Samoa"],
  ["美属维尔京群岛", "VI", "US Virgin Islands"],
  ["蒙古", "MN", "Mongolia"],
  ["蒙特塞拉特", "MS", "Montserrat"],
  ["孟加拉国", "BD", "Bangladesh"],
  ["秘鲁", "PE", "Peru"],
  ["密克罗尼西亚", "FM", "Micronesia"],
  ["缅甸", "MM", "Myanmar"],
  ["摩尔多瓦", "MD", "Moldova"],
  ["摩洛哥", "MA", "Morocco"],
  ["摩纳哥", "MC", "Monaco"],
  ["莫桑比克", "MZ", "Mozambique"],
  ["纳米比亚", "NA", "Namibia"],
  ["南极洲", "AQ", "Antarctica"],
  ["南乔治亚和南桑威奇群岛", "GS", "South Georgia and the South Sandwich Islands"],
  ["南苏丹", "SS", "South Sudan"],
  ["瑙鲁", "NR", "Nauru"],
  ["尼加拉瓜", "NI", "Nicaragua"],
  ["尼泊尔", "NP", "Nepal"],
  ["尼日尔", "NE", "Niger"],
  ["尼日利亚", "NG", "Nigeria"],
  ["纽埃", "NU", "Niue"],
  ["挪威", "NO", "Norway"],
  ["诺福克岛", "NF", "Norfolk Island"],
  ["帕劳", "PW", "Palau"],
  ["皮特凯恩群岛", "PN", "Pitcairn Islands"],
  ["葡萄牙", "PT", "Portugal"],
  ["萨尔瓦多", "SV", "El Salvador"],
  ["萨摩亚", "WS", "Samoa"],
  ["塞尔维亚", "RS", "Serbia"],
  ["塞拉利昂", "SL", "Sierra Leone"],
  ["塞内加尔", "SN", "Senegal"],
  ["塞浦路斯", "CY", "Cyprus"],
  ["塞舌尔", "SC", "Seychelles"],
  ["圣巴泰勒米", "BL", "Saint Barthelemy"],
  ["圣诞岛", "CX", "Christmas Island"],
  ["圣多美和普林西比", "ST", "Sao Tome and Principe"],
  ["圣赫勒拿", "SH", "Saint Helena"],
  ["圣基茨和尼维斯", "KN", "Saint Kitts and Nevis"],
  ["圣卢西亚", "LC", "Saint Lucia"],
  ["圣马力诺", "SM", "San Marino"],
  ["圣皮埃尔和密克隆", "PM", "Saint Pierre and Miquelon"],
  ["圣文森特和格林纳丁斯", "VC", "Saint Vincent and the Grenadines"],
  ["斯里兰卡", "LK", "Sri Lanka"],
  ["斯洛伐克", "SK", "Slovakia"],
  ["斯洛文尼亚", "SI", "Slovenia"],
  ["斯瓦尔巴和扬马延", "SJ", "Svalbard and Jan Mayen"],
  ["斯威士兰", "SZ", "Eswatini", "Swaziland"],
  ["苏丹", "SD", "Sudan"],
  ["苏里南", "SR", "Suriname"],
  ["所罗门群岛", "SB", "Solomon Islands"],
  ["索马里", "SO", "Somalia"],
  ["塔吉克斯坦", "TJ", "Tajikistan"],
  ["坦桑尼亚", "TZ", "Tanzania"],
  ["汤加", "TO", "Tonga"],
  ["特克斯和凯科斯群岛", "TC", "Turks and Caicos Islands"],
  ["特立尼达和多巴哥", "TT", "Trinidad and Tobago"],
  ["突尼斯", "TN", "Tunisia"],
  ["图瓦卢", "TV", "Tuvalu"],
  ["土库曼斯坦", "TM", "Turkmenistan"],
  ["托克劳", "TK", "Tokelau"],
  ["瓦利斯和富图纳", "WF", "Wallis and Futuna"],
  ["瓦努阿图", "VU", "Vanuatu"],
  ["危地马拉", "GT", "Guatemala"],
  ["委内瑞拉", "VE", "Venezuela"],
  ["文莱", "BN", "Brunei"],
  ["乌干达", "UG", "Uganda"],
  ["乌克兰", "UA", "Ukraine"],
  ["乌拉圭", "UY", "Uruguay"],
  ["乌兹别克斯坦", "UZ", "Uzbekistan"],
  ["西撒哈拉", "EH", "Western Sahara"],
  ["希腊", "GR", "Greece"],
  ["新喀里多尼亚", "NC", "New Caledonia"],
  ["叙利亚", "SY", "Syria"],
  ["牙买加", "JM", "Jamaica"],
  ["亚美尼亚", "AM", "Armenia"],
  ["也门", "YE", "Yemen"],
  ["伊拉克", "IQ", "Iraq"],
  ["伊朗", "IR", "Iran"],
  ["英属维尔京群岛", "VG", "British Virgin Islands"],
  ["英属印度洋领地", "IO", "British Indian Ocean Territory"],
  ["约旦", "JO", "Jordan"],
  ["赞比亚", "ZM", "Zambia"],
  ["泽西岛", "JE", "Jersey"],
  ["乍得", "TD", "Chad"],
  ["直布罗陀", "GI", "Gibraltar"],
  ["智利", "CL", "Chile"],
  ["中非", "CF", "Central African Republic"],
]
