-- customerinfo / vendorinfo 全部列补充业务注释（与当前 EF 模型一致，可单独在库上重复执行）

COMMENT ON TABLE public.customerinfo IS '客户主表：公司档案、授信、归属、审核与软删除等核心信息';

COMMENT ON COLUMN public.customerinfo."CustomerId" IS '客户主键（GUID）；销售订单、出库通知、联系人/地址/银行等子表外键指向此列';
COMMENT ON COLUMN public.customerinfo."CustomerCode" IS '客户业务编码（唯一，如 CUST 流水号）；列表检索与单据关联';
COMMENT ON COLUMN public.customerinfo."OfficialName" IS '公司全称（中文注册/常用名称）';
COMMENT ON COLUMN public.customerinfo."StandardOfficialName" IS '公司标准全称（规范化后的正式名称，可与 OfficialName 区分）';
COMMENT ON COLUMN public.customerinfo."EnglishOfficialName" IS '公司英文全称';
COMMENT ON COLUMN public.customerinfo."NickName" IS '公司简称（列表展示、检索友好名）';
COMMENT ON COLUMN public.customerinfo."Level" IS '客户等级：1=D 2=C 3=B 4=BPO 5=VIP 6=VPO';
COMMENT ON COLUMN public.customerinfo."Type" IS '客户类型：1=OEM 2=ODM 3=终端 4=IDH 5=贸易商 6=代理商 7=EMS 8=非行业 9=科研机构 10=供应链 11=原厂';
COMMENT ON COLUMN public.customerinfo."Scale" IS '规模（数据字典编码 smallint）';
COMMENT ON COLUMN public.customerinfo."Background" IS '背景（数据字典编码 smallint）';
COMMENT ON COLUMN public.customerinfo."DealMode" IS '交易模式（数据字典编码 smallint）';
COMMENT ON COLUMN public.customerinfo."CompanyNature" IS '公司性质（数据字典编码 smallint）';
COMMENT ON COLUMN public.customerinfo."Country" IS '国家/地区类型编码（如 1=中国 2=海外，具体见数据字典）';
COMMENT ON COLUMN public.customerinfo."Industry" IS '所属行业（文本或字典展示名）';
COMMENT ON COLUMN public.customerinfo."Product" IS '主营产品';
COMMENT ON COLUMN public.customerinfo."Product2" IS '主营产品2（补充产品线）';
COMMENT ON COLUMN public.customerinfo."Application" IS '应用领域';
COMMENT ON COLUMN public.customerinfo."TradeCurrency" IS '交易币别（CurrencyCode 等数据字典编码）';
COMMENT ON COLUMN public.customerinfo."TradeType" IS '交易方式（数据字典编码 smallint）';
COMMENT ON COLUMN public.customerinfo."Payment" IS '账期天数（PaymentTerms，如 30/60/90）';
COMMENT ON COLUMN public.customerinfo."ExternalNumber" IS '外部系统/ERP 客户编号（对接冗余）';
COMMENT ON COLUMN public.customerinfo."CreditLine" IS '授信额度（numeric(18,2)，审批后额度上限）';
COMMENT ON COLUMN public.customerinfo."CreditLineRemain" IS '授信额度剩余/可用余额（numeric(18,2)，随业务占用回写）';
COMMENT ON COLUMN public.customerinfo."AscriptionType" IS '客户归属：1=专属（绑定业务员） 2=公海（可领取/分配）';
COMMENT ON COLUMN public.customerinfo."ProtectStatus" IS '是否处于保护期（true=受保护，公海规则下不可被他人领取）';
COMMENT ON COLUMN public.customerinfo."ProtectFromUserId" IS '保护发起人用户主键（GUID）';
COMMENT ON COLUMN public.customerinfo."ProtectTime" IS '保护开始/生效时间（timestamptz，UTC）';
COMMENT ON COLUMN public.customerinfo."Status" IS '客户状态：1=新建 2=待审核 10=已审核 12=待财务审核 20=财务建档 -1=审核失败';
COMMENT ON COLUMN public.customerinfo."AuditRemark" IS '审核驳回原因（Status=-1 时由审批人填写）';
COMMENT ON COLUMN public.customerinfo."BlackList" IS '是否黑名单客户（true=禁止正常交易）';
COMMENT ON COLUMN public.customerinfo."DisenableStatus" IS '是否禁用/冻结（true=停用，不影响历史单据追溯）';
COMMENT ON COLUMN public.customerinfo."DisenableType" IS '禁用类型（数据字典编码 smallint）';
COMMENT ON COLUMN public.customerinfo."CommonSeaAuditStatus" IS '公海相关审核状态（领取/释放等流程编码）';
COMMENT ON COLUMN public.customerinfo."Longitude" IS '公司位置经度（numeric(10,6)，地图选点）';
COMMENT ON COLUMN public.customerinfo."Latitude" IS '公司位置纬度（numeric(10,6)，地图选点）';
COMMENT ON COLUMN public.customerinfo."CompanyInfo" IS '公司简介（长文本，与 Remark 备注区分）';
COMMENT ON COLUMN public.customerinfo."Remark" IS '备注（varchar(500)，内部说明；前端字段名 remarks）';
COMMENT ON COLUMN public.customerinfo."DUNS" IS '邓白氏码（D-U-N-S Number）';
COMMENT ON COLUMN public.customerinfo."IsControl" IS '是否管控客户（true=需额外审批或限制下单）';
COMMENT ON COLUMN public.customerinfo."CreditCode" IS '统一社会信用代码（可含分隔符，最长 50 字符）';
COMMENT ON COLUMN public.customerinfo."IdentityType" IS '客户身份类型（数据字典编码 smallint）';
COMMENT ON COLUMN public.customerinfo."SalesUserId" IS '负责业务员用户主键（GUID，关联系统用户）';
COMMENT ON COLUMN public.customerinfo."Province" IS '省/州';
COMMENT ON COLUMN public.customerinfo."City" IS '市';
COMMENT ON COLUMN public.customerinfo."District" IS '区/县';
COMMENT ON COLUMN public.customerinfo."IsDeleted" IS '软删除标记（true=逻辑删除，常规查询应排除）';
COMMENT ON COLUMN public.customerinfo."DeletedAt" IS '软删除时间（timestamptz，UTC）';
COMMENT ON COLUMN public.customerinfo."DeletedByUserId" IS '执行软删除的用户主键（GUID）';
COMMENT ON COLUMN public.customerinfo."DeletedByUserName" IS '执行软删除的用户展示名（冗余快照）';
COMMENT ON COLUMN public.customerinfo."DeleteReason" IS '删除理由';
COMMENT ON COLUMN public.customerinfo."BlackListReason" IS '加入黑名单原因';
COMMENT ON COLUMN public.customerinfo."BlackListAt" IS '加入黑名单时间（timestamptz，UTC）';
COMMENT ON COLUMN public.customerinfo."BlackListByUserId" IS '加入黑名单操作人用户主键（GUID）';
COMMENT ON COLUMN public.customerinfo."BlackListByUserName" IS '加入黑名单操作人展示名（冗余快照）';
COMMENT ON COLUMN public.customerinfo."CreateTime" IS '记录创建时间（timestamptz，UTC）';
COMMENT ON COLUMN public.customerinfo."CreateUserId" IS '历史创建人 bigint（旧体系审计字段；业务追溯请优先 create_by_user_id）';
COMMENT ON COLUMN public.customerinfo."ModifyTime" IS '记录最后修改时间（timestamptz，UTC）';
COMMENT ON COLUMN public.customerinfo."ModifyUserId" IS '历史最后修改人 bigint（旧体系审计字段）';
COMMENT ON COLUMN public.customerinfo.create_by_user_id IS '创建本客户时的登录用户 GUID（JWT 用户主键，审计与权限追溯）';
COMMENT ON COLUMN public.customerinfo.modify_by_user_id IS '最后修改本客户时的登录用户 GUID';

COMMENT ON TABLE public.vendorinfo IS '供应商主表：采购档案、评级、归属、审核与软删除等核心信息';

COMMENT ON COLUMN public.vendorinfo."VendorId" IS '供应商主键（GUID）；采购订单、到货通知、联系人/地址/银行等子表外键指向此列';
COMMENT ON COLUMN public.vendorinfo."Code" IS '供应商业务编码（唯一，如 VEND 流水号）；列表检索与单据关联';
COMMENT ON COLUMN public.vendorinfo."OfficialName" IS '公司全称（中文注册/常用名称）';
COMMENT ON COLUMN public.vendorinfo."NickName" IS '公司简称（列表展示、检索友好名）';
COMMENT ON COLUMN public.vendorinfo."EnglishOfficialName" IS '公司英文全称';
COMMENT ON COLUMN public.vendorinfo."VendorIdCrm" IS 'CRM/外部系统供应商 ID（对接冗余）';
COMMENT ON COLUMN public.vendorinfo."Level" IS '供应商等级（VendorLevelCode 数据字典编码）';
COMMENT ON COLUMN public.vendorinfo."Scale" IS '规模（数据字典编码 smallint）';
COMMENT ON COLUMN public.vendorinfo."Background" IS '背景（数据字典编码 smallint）';
COMMENT ON COLUMN public.vendorinfo."CompanyClass" IS '公司分类（数据字典编码 smallint）';
COMMENT ON COLUMN public.vendorinfo."Country" IS '国家/地区类型编码（数据字典 smallint）';
COMMENT ON COLUMN public.vendorinfo."LocationType" IS '地域类型（如境内/境外，数据字典编码）';
COMMENT ON COLUMN public.vendorinfo."Industry" IS '所属行业（文本或字典展示名）';
COMMENT ON COLUMN public.vendorinfo."Product" IS '主营产品/供应品类';
COMMENT ON COLUMN public.vendorinfo."OfficeAddress" IS '办公地址（单行文本；多地址见 vendoraddress 子表）';
COMMENT ON COLUMN public.vendorinfo."TradeCurrency" IS '交易币别（CurrencyCode 等数据字典编码）';
COMMENT ON COLUMN public.vendorinfo."TradeType" IS '交易方式（数据字典编码 smallint）';
COMMENT ON COLUMN public.vendorinfo."Payment" IS '账期天数（如 30/60/90，与 PaymentMethod 付款方式区分）';
COMMENT ON COLUMN public.vendorinfo."ExternalNumber" IS '外部系统/ERP 供应商编号（对接冗余）';
COMMENT ON COLUMN public.vendorinfo."Credit" IS '供应商身份/信用等级（VendorIdentityCode 数据字典编码，存于 Credit 列）';
COMMENT ON COLUMN public.vendorinfo."QualityPrejudgement" IS '质量预判评级（数据字典编码 smallint）';
COMMENT ON COLUMN public.vendorinfo."Traceability" IS '可追溯性评级（数据字典编码 smallint）';
COMMENT ON COLUMN public.vendorinfo."AfterSalesService" IS '售后服务评级（数据字典编码 smallint）';
COMMENT ON COLUMN public.vendorinfo."DegreeAdaptability" IS '适应程度/配合度评级（数据字典编码 smallint）';
COMMENT ON COLUMN public.vendorinfo."ISCPFlag" IS '是否 ISCP 相关供应商（boolean 标志位）';
COMMENT ON COLUMN public.vendorinfo."Strategy" IS '战略属性（数据字典编码 smallint）';
COMMENT ON COLUMN public.vendorinfo."SelfSupport" IS '是否自营（true=自营供应商）';
COMMENT ON COLUMN public.vendorinfo."BlackList" IS '是否黑名单供应商（true=禁止正常采购）';
COMMENT ON COLUMN public.vendorinfo."IsDisenable" IS '是否禁用/冻结（true=停用，不影响历史单据追溯）';
COMMENT ON COLUMN public.vendorinfo."Longitude" IS '公司位置经度（numeric(10,6)，地图选点）';
COMMENT ON COLUMN public.vendorinfo."Latitude" IS '公司位置纬度（numeric(10,6)，地图选点）';
COMMENT ON COLUMN public.vendorinfo."CompanyInfo" IS '公司简介（长文本，名片/AI 解析等可写入）';
COMMENT ON COLUMN public.vendorinfo."Remark" IS '其他备注（text，与 CompanyInfo 公司简介区分）';
COMMENT ON COLUMN public.vendorinfo."Website" IS '官方网站 URL';
COMMENT ON COLUMN public.vendorinfo."PurchaserName" IS '负责采购员展示名（非用户表关联时可填文本）';
COMMENT ON COLUMN public.vendorinfo."PaymentMethod" IS '付款方式编码（如 Prepaid、TT 等，与账期天数 Payment 区分）';
COMMENT ON COLUMN public.vendorinfo."ListingCode" IS '上市代码/股票代码';
COMMENT ON COLUMN public.vendorinfo."VendorScope" IS '经营范围';
COMMENT ON COLUMN public.vendorinfo."IsControl" IS '是否管控供应商（true=需额外审批或限制下单）';
COMMENT ON COLUMN public.vendorinfo."CreditCode" IS '统一社会信用代码';
COMMENT ON COLUMN public.vendorinfo."AscriptionType" IS '供应商归属：1=专属（绑定采购员） 2=公海（可领取/分配）';
COMMENT ON COLUMN public.vendorinfo."PurchaseUserId" IS '负责采购员用户主键（GUID，关联系统用户）';
COMMENT ON COLUMN public.vendorinfo."PurchaseGroupId" IS '采购员组/采购组主键（GUID）';
COMMENT ON COLUMN public.vendorinfo."Status" IS '供应商状态：1=新建 2=待审核 10=已审核 12=待财务审核 20=财务建档 -1=审核失败';
COMMENT ON COLUMN public.vendorinfo."AuditRemark" IS '审核驳回原因（Status=-1 时由审批人填写）';
COMMENT ON COLUMN public.vendorinfo."IsDeleted" IS '软删除标记（true=逻辑删除，常规查询应排除）';
COMMENT ON COLUMN public.vendorinfo."DeleteTime" IS '软删除时间（timestamptz，UTC）';
COMMENT ON COLUMN public.vendorinfo."DeleteReason" IS '删除原因';
COMMENT ON COLUMN public.vendorinfo."CreateTime" IS '记录创建时间（timestamptz，UTC）';
COMMENT ON COLUMN public.vendorinfo."CreateUserId" IS '历史创建人 bigint（旧体系审计字段；业务追溯请优先 create_by_user_id）';
COMMENT ON COLUMN public.vendorinfo."ModifyTime" IS '记录最后修改时间（timestamptz，UTC）';
COMMENT ON COLUMN public.vendorinfo."ModifyUserId" IS '历史最后修改人 bigint（旧体系审计字段）';
COMMENT ON COLUMN public.vendorinfo.create_by_user_id IS '创建本供应商时的登录用户 GUID（JWT 用户主键，审计与权限追溯）';
COMMENT ON COLUMN public.vendorinfo.modify_by_user_id IS '最后修改本供应商时的登录用户 GUID';
